export { default as GoogleIcon } from './GoogleIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as ErrorIcon } from './ErrorIcon'
export { default as ValidIcon } from './ValidIcon'
export { default as WhatsappIcon } from './WhatsappIcon'
